- name: wp-install
  hosts: '{{ HOST }}'
  become: yes

  vars:
    packg: 
      - apache2 
      - ghostscript 
      - libapache2-mod-php 
      - mysql-server 
      - php 
      - php-bcmath 
      - php-curl 
      - php-imagick 
      - php-intl 
      - php-json 
      - php-mbstring 
      - php-mysql 
      - php-xml 
      - php-zip
      - python3-pymysql
    
    ansible_mysql_login_user: root
    ansible_mysql_login_password: "qwerty123"
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_password: "qwerty123"  

  tasks:
    - name: installing dependencies 
      apt:
        update_cache: yes
        pkg: "{{ packg }}"
        state: present

      when: ansible_os_family == 'Debian'

    - name: creating /srv/www
      file:
        path: /srv/www
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      when: ansible_os_family == 'Debian'

    - name: extracting wp
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /srv/www
        remote_src: yes
        creates: /srv/www/wp-config-sample.php
      notify: Set permissions
      when: ansible_os_family == 'Debian'
  
    - name: creating wp-conf
      copy:
        dest: /etc/apache2/sites-available/wordpress.conf
        content: |
          <VirtualHost *:80>
             DocumentRoot /srv/www/wordpress
             <Directory /srv/www/wordpress>
                 Options FollowSymLinks
                 AllowOverride Limit Options FileInfo
                 DirectoryIndex index.php
                 Require all granted
             </Directory>
             <Directory /srv/www/wordpress/wp-content>
                 Options FollowSymLinks
                 Require all granted
             </Directory>
          </VirtualHost>
      notify: Reload apache2
      when: ansible_os_family == 'Debian'
    
    - name: enabling wp-site
      command: a2ensite wordpress
      notify: Reload apache2
      when: ansible_os_family == 'Debian'      
  
    - name: rewrite 
      command: a2enmod rewrite
      notify: Reload apache2
      when: ansible_os_family == 'Debian'

    - name: disable its works   
      command: a2dissite 000-default
      notify: Reload apache2
      when: ansible_os_family == 'Debian'

    - name: create mysql db
      mysql_db:
        name: "{{ wp_db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: ansible_os_family == 'Debian'

    - name: create db user
      mysql_user:
        name: "{{ wp_db_user }}"
        host: localhost
        password: "{{ wp_db_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      notify: Start MYSQL
      when: ansible_os_family == 'Debian'

    - name: copy sample config
      copy:
        src: /srv/www/wordpress/wp-config-sample.php
        dest: /srv/www/wordpress/wp-config.php
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0644'
      become: yes
      when: ansible_os_family == 'Debian'

    - name: set db-name
      lineinfile:
        path: /srv/www/wordpress/wp-config.php
        regexp: "define\\(\\s*'DB_NAME'.*"
        line: "define('DB_NAME', '{{ wp_db_name }}');"
        owner: www-data
        group: www-data
        mode: '0644'
      become: yes
      when: ansible_os_family == 'Debian'  
      
    - name: set db-user
      lineinfile:
        path: /srv/www/wordpress/wp-config.php
        regexp: "define\\(\\s*'DB_USER'.*"
        line: "define('DB_USER', '{{ wp_db_user }}');"
        owner: www-data
        group: www-data
        mode: '0644'
      become: yes
      when: ansible_os_family == 'Debian'
        
      
    - name: set db-passwd
      lineinfile:
        path: /srv/www/wordpress/wp-config.php
        regexp: "define\\(\\s*'DB_PASSWORD'.*"
        line: "define('DB_PASSWORD', '{{ wp_db_password }}');"
        owner: www-data
        group: www-data
        mode: '0644'
      become: yes
      when: ansible_os_family == 'Debian'
      
  handlers:
    - name: Set permissions
      file:
        path: /srv/www
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      when: ansible_os_family == 'Debian'

    - name: Reload apache2
      service:
        name: apache2
        state: reloaded
      when: ansible_os_family == 'Debian'

    - name: Start MYSQL
      service:
        name: mysql
        state: started
      when: ansible_os_family == 'Debian'
