---
  - hosts: '{{ HOST }}' 
    become: yes
    tasks:
      - name: Install dependencies
        apt:
          name: ['php-mysql',]
          state: present
          update_cache: true
        when: ansible_os_family == 'Debian'

      - name: Install Apache Debian family
        apt:
          name: apache2       
          state: present
          update_cache: true
        when: ansible_os_family == 'Debian'

      - name: Run Apache Debian family
        service:
          name: apache2
          state: started
          enabled: yes
        when: ansible_os_family == 'Debian'
